---
sudo: false
language: ruby
cache: bundler

rvm:
  - 2.3
  - 2.4
  - 2.5

before_install:
  - gem install bundler
  - rvm install 2.3
  - rvm install 2.4
  - rvm install 2.5

branches:
  only:
    - master
